### ISSUE TITLE
Use setTimeout instead of setInterval

### ISSUE THREAD

**Issue by nukkamoto** [rajanlagah/react-internet-meter#5]
```
let timer;
function callMe(){
   if(timer) clearTimeout(timer);
   /// some logic()
   
   timer = setTimeout( callMe, inverval);
}

callMe(); //initialises it
```

This will improve the accuracy of your reporting....
At the moment slow connections, will find it increasingly more difficult to catch up with the last reported connection, because the image is queued up and pending to be loaded. Creating a waterfall queue of requests.

The above will ensure that we only check for next once the previous image finished downloading.

Lastly this will introduce an issue when the network is really slow.... that the response takes longer than the frequency, but that's ok.
or you can have a start time, finish time to report midway an image loading ... that this image is taking too long therefore slow network.

**Comment by rajanlagah** [comment]
Yes totally agree with your point. 
Will update it as soon as I get time. 
Thank you for sharing. 👍

**Comment by rajanlagah** [comment]
@valtido 
Released ( https://github.com/rajanlagah/react-internet-meter/pull/6 )
Version 1.1.0 ( https://www.npmjs.com/package/react-internet-meter )
